name: Gendiff CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip
      - run: |
          pip install poetry
          make install
      - run: make lint
      - name: test coverage  
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTED_ID }}
        with:
          coverageCommand: make test-cov
          debug: true